on: [push]

jobs:
  salesforce-job:
    runs-on: ubuntu-latest
    name: Deployment and test job
    steps:
      - name: Acci√≥n de Despliegue
        id: despliegue
        uses: actions/action-despliegue@v2
      #  with:
      #    who-to-greet: 'Mona the Octocat'
